// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: internal/proto/pb/homewire.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_AttachmentType int32

const (
	Message_IMAGE Message_AttachmentType = 0
	Message_VIDEO Message_AttachmentType = 1
	Message_AUDIO Message_AttachmentType = 2
)

// Enum value maps for Message_AttachmentType.
var (
	Message_AttachmentType_name = map[int32]string{
		0: "IMAGE",
		1: "VIDEO",
		2: "AUDIO",
	}
	Message_AttachmentType_value = map[string]int32{
		"IMAGE": 0,
		"VIDEO": 1,
		"AUDIO": 2,
	}
)

func (x Message_AttachmentType) Enum() *Message_AttachmentType {
	p := new(Message_AttachmentType)
	*p = x
	return p
}

func (x Message_AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_pb_homewire_proto_enumTypes[0].Descriptor()
}

func (Message_AttachmentType) Type() protoreflect.EnumType {
	return &file_internal_proto_pb_homewire_proto_enumTypes[0]
}

func (x Message_AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_AttachmentType.Descriptor instead.
func (Message_AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{4, 0}
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Introduction
	//	*Envelope_WireAnnouncement
	//	*Envelope_WireList
	//	*Envelope_Message
	Payload isEnvelope_Payload `protobuf_oneof:"Payload"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_homewire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_homewire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{0}
}

func (m *Envelope) GetPayload() isEnvelope_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Envelope) GetPing() string {
	if x, ok := x.GetPayload().(*Envelope_Ping); ok {
		return x.Ping
	}
	return ""
}

func (x *Envelope) GetPong() string {
	if x, ok := x.GetPayload().(*Envelope_Pong); ok {
		return x.Pong
	}
	return ""
}

func (x *Envelope) GetIntroduction() *Introduction {
	if x, ok := x.GetPayload().(*Envelope_Introduction); ok {
		return x.Introduction
	}
	return nil
}

func (x *Envelope) GetWireAnnouncement() *BasicWireInfo {
	if x, ok := x.GetPayload().(*Envelope_WireAnnouncement); ok {
		return x.WireAnnouncement
	}
	return nil
}

func (x *Envelope) GetWireList() *WireList {
	if x, ok := x.GetPayload().(*Envelope_WireList); ok {
		return x.WireList
	}
	return nil
}

func (x *Envelope) GetMessage() *Message {
	if x, ok := x.GetPayload().(*Envelope_Message); ok {
		return x.Message
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Ping struct {
	Ping string `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong string `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type Envelope_Introduction struct {
	Introduction *Introduction `protobuf:"bytes,3,opt,name=introduction,proto3,oneof"`
}

type Envelope_WireAnnouncement struct {
	WireAnnouncement *BasicWireInfo `protobuf:"bytes,4,opt,name=wireAnnouncement,proto3,oneof"`
}

type Envelope_WireList struct {
	WireList *WireList `protobuf:"bytes,5,opt,name=wireList,proto3,oneof"`
}

type Envelope_Message struct {
	Message *Message `protobuf:"bytes,6,opt,name=message,proto3,oneof"`
}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_Introduction) isEnvelope_Payload() {}

func (*Envelope_WireAnnouncement) isEnvelope_Payload() {}

func (*Envelope_WireList) isEnvelope_Payload() {}

func (*Envelope_Message) isEnvelope_Payload() {}

type Introduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayedName string           `protobuf:"bytes,2,opt,name=displayedName,proto3" json:"displayedName,omitempty"`
	PublicKey     []byte           `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Wires         []*BasicWireInfo `protobuf:"bytes,4,rep,name=wires,proto3" json:"wires,omitempty"`
}

func (x *Introduction) Reset() {
	*x = Introduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_homewire_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Introduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Introduction) ProtoMessage() {}

func (x *Introduction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_homewire_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Introduction.ProtoReflect.Descriptor instead.
func (*Introduction) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{1}
}

func (x *Introduction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Introduction) GetDisplayedName() string {
	if x != nil {
		return x.DisplayedName
	}
	return ""
}

func (x *Introduction) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Introduction) GetWires() []*BasicWireInfo {
	if x != nil {
		return x.Wires
	}
	return nil
}

type BasicWireInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BasicWireInfo) Reset() {
	*x = BasicWireInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_homewire_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicWireInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicWireInfo) ProtoMessage() {}

func (x *BasicWireInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_homewire_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicWireInfo.ProtoReflect.Descriptor instead.
func (*BasicWireInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{2}
}

func (x *BasicWireInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BasicWireInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WireList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wires []*BasicWireInfo `protobuf:"bytes,1,rep,name=wires,proto3" json:"wires,omitempty"`
}

func (x *WireList) Reset() {
	*x = WireList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_homewire_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WireList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireList) ProtoMessage() {}

func (x *WireList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_homewire_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireList.ProtoReflect.Descriptor instead.
func (*WireList) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{3}
}

func (x *WireList) GetWires() []*BasicWireInfo {
	if x != nil {
		return x.Wires
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       string              `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Attachment *Message_Attachment `protobuf:"bytes,2,opt,name=attachment,proto3,oneof" json:"attachment,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_homewire_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_homewire_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetAttachment() *Message_Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type Message_Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Message_AttachmentType `protobuf:"varint,1,opt,name=type,proto3,enum=Message_AttachmentType" json:"type,omitempty"`
	Data *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Message_Attachment) Reset() {
	*x = Message_Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_pb_homewire_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Attachment) ProtoMessage() {}

func (x *Message_Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pb_homewire_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Attachment.ProtoReflect.Descriptor instead.
func (*Message_Attachment) Descriptor() ([]byte, []int) {
	return file_internal_proto_pb_homewire_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Message_Attachment) GetType() Message_AttachmentType {
	if x != nil {
		return x.Type
	}
	return Message_IMAGE
}

func (x *Message_Attachment) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_proto_pb_homewire_proto protoreflect.FileDescriptor

var file_internal_proto_pb_homewire_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02,
	0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x12, 0x14, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x33, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x49,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x10, 0x77,
	0x69, 0x72, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x57, 0x69, 0x72,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x10, 0x77, 0x69, 0x72, 0x65, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x77, 0x69, 0x72,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x57, 0x69,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x77, 0x69, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x77, 0x69, 0x72, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x57,
	0x69, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x77, 0x69, 0x72, 0x65, 0x73, 0x22, 0x33,
	0x0a, 0x0d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x57, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x08, 0x57, 0x69, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x05, 0x77, 0x69, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x57, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x77, 0x69, 0x72, 0x65, 0x73, 0x22, 0xfe, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x1a,
	0x63, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x02, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x13, 0x5a, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_pb_homewire_proto_rawDescOnce sync.Once
	file_internal_proto_pb_homewire_proto_rawDescData = file_internal_proto_pb_homewire_proto_rawDesc
)

func file_internal_proto_pb_homewire_proto_rawDescGZIP() []byte {
	file_internal_proto_pb_homewire_proto_rawDescOnce.Do(func() {
		file_internal_proto_pb_homewire_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_pb_homewire_proto_rawDescData)
	})
	return file_internal_proto_pb_homewire_proto_rawDescData
}

var file_internal_proto_pb_homewire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_pb_homewire_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_pb_homewire_proto_goTypes = []interface{}{
	(Message_AttachmentType)(0), // 0: Message.AttachmentType
	(*Envelope)(nil),            // 1: Envelope
	(*Introduction)(nil),        // 2: Introduction
	(*BasicWireInfo)(nil),       // 3: BasicWireInfo
	(*WireList)(nil),            // 4: WireList
	(*Message)(nil),             // 5: Message
	(*Message_Attachment)(nil),  // 6: Message.Attachment
	(*anypb.Any)(nil),           // 7: google.protobuf.Any
}
var file_internal_proto_pb_homewire_proto_depIdxs = []int32{
	2, // 0: Envelope.introduction:type_name -> Introduction
	3, // 1: Envelope.wireAnnouncement:type_name -> BasicWireInfo
	4, // 2: Envelope.wireList:type_name -> WireList
	5, // 3: Envelope.message:type_name -> Message
	3, // 4: Introduction.wires:type_name -> BasicWireInfo
	3, // 5: WireList.wires:type_name -> BasicWireInfo
	6, // 6: Message.attachment:type_name -> Message.Attachment
	0, // 7: Message.Attachment.type:type_name -> Message.AttachmentType
	7, // 8: Message.Attachment.data:type_name -> google.protobuf.Any
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_internal_proto_pb_homewire_proto_init() }
func file_internal_proto_pb_homewire_proto_init() {
	if File_internal_proto_pb_homewire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_pb_homewire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_homewire_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Introduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_homewire_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicWireInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_homewire_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WireList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_homewire_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_pb_homewire_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_proto_pb_homewire_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Introduction)(nil),
		(*Envelope_WireAnnouncement)(nil),
		(*Envelope_WireList)(nil),
		(*Envelope_Message)(nil),
	}
	file_internal_proto_pb_homewire_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_pb_homewire_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_pb_homewire_proto_goTypes,
		DependencyIndexes: file_internal_proto_pb_homewire_proto_depIdxs,
		EnumInfos:         file_internal_proto_pb_homewire_proto_enumTypes,
		MessageInfos:      file_internal_proto_pb_homewire_proto_msgTypes,
	}.Build()
	File_internal_proto_pb_homewire_proto = out.File
	file_internal_proto_pb_homewire_proto_rawDesc = nil
	file_internal_proto_pb_homewire_proto_goTypes = nil
	file_internal_proto_pb_homewire_proto_depIdxs = nil
}
